name: Deploy Prod
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deployment auto
    runs-on: ubuntu-latest
    steps: 

      - name: SSH Remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GOORM_HOST }}
          username: ${{ secrets.GOORM_USER }}
          key: ${{ secrets.GOORM_KEY }}
          port: ${{ secrets.GOORM_PORT }}
          script: ls -al