name: Deploy Prod
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deployment auto
    runs-on: ubuntu-latest
    steps: 
      - name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: ${{ SSH_HOST }}
          user: ${{ SSH_USER }}
          key: ${{ SSH_KEY }}
          command: cd /workspace/barianbarbar/test-auto-pull && git pull origin main