name: Deploy Prod
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deployment auto
    runs-on: ubuntu-latest
    steps: 
      - name: SSH Remote PROXMOX
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROXMOX_HOST }}
          username: ${{ secrets.PROXMOX_USER }}
          key: ${{ secrets.PROXMOX_KEY }}
          port: ${{ secrets.PROXMOX_PORT }}
          script: |
            cd test-auto-pull
            git fetch
            git reset --hard HEAD
            git merge origin/main
            git pull
            npm install
            